import type { Metadata } from "next";
import { LoadingCursor } from "@/components/ui/loading-cursor";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className="h-full font-sans antialiased"
    >
      <body className="min-h-full flex flex-col">{children}<LoadingCursor /></body>
    </html>
  );
}
